name: Compiler SCSS en CSS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-css:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer Dart Sass
        run: npm install -g sass

      - name: Compiler SCSS en CSS
        run: sass scss/styles.scss css/styles.css

      - name: Commit et push du CSS compilé
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add css/styles.css
          git commit -m "Compile SCSS en CSS via GitHub Actions" || echo "Pas de changements à commit"
          git push
